"""add vector_id uuid and pdf page metrics

Revision ID: 03d0e5acbd75
Revises: 8f74d8ed6718
Create Date: 2026-10-04 17:31:05.860577

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03d0e5acbd75"
down_revision: Union[str, Sequence[str], None] = "8f74d8ed6718"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chunks",
        "vector_id",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Uuid(),
        existing_nullable=True,
        postgresql_using="vector_id::uuid",
    )  # Postgres vägrar gissa text. Med hårdkodad anvisning tvingar man fram ett uuid.
    op.create_index(op.f("ix_chunks_vector_id"), "chunks", ["vector_id"], unique=True)
    op.add_column("documents", sa.Column("page_count", sa.Integer(), nullable=True))
    op.add_column(
        "documents", sa.Column("empty_page_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "documents", sa.Column("short_page_count", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "short_page_count")
    op.drop_column("documents", "empty_page_count")
    op.drop_column("documents", "page_count")
    op.drop_index(op.f("ix_chunks_vector_id"), table_name="chunks")
    op.alter_column(
        "chunks",
        "vector_id",
        existing_type=sa.Uuid(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
