"""add failure_reason to documents

Revision ID: 3265b011cf26
Revises: 04a60e3452ef
Create Date: 2026-09-04 21:29:17.192802

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3265b011cf26"
down_revision: Union[str, Sequence[str], None] = "04a60e3452ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "failure_reason",
            sa.Enum(
                "SOURCE_MISSING",
                "UNREADABLE_SOURCE",
                "NO_TEXT_EXTRACTED",
                "TEXT_BELOW_THRESHOLD",
                name="failurereason",
                native_enum=False,
            ),
            nullable=True,
        ),
    )
    op.alter_column(
        "documents",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "PENDING",
            "EXTRACTED",
            "EMBEDDED",
            "FAILED",
            name="documentstatus",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents",
        "status",
        existing_type=sa.Enum(
            "PENDING",
            "EXTRACTED",
            "EMBEDDED",
            "FAILED",
            name="documentstatus",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_column("documents", "failure_reason")
    # ### end Alembic commands ###
