"""make chunks for vector_id not null

Revision ID: 3e2f1c194263
Revises: 03d0e5acbd75
Create Date: 2026-10-04 19:35:57.190448

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e2f1c194263"
down_revision: Union[str, Sequence[str], None] = "03d0e5acbd75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chunks", "vector_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chunks", "vector_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
