"""add source_files and courses tables

Revision ID: 8f74d8ed6718
Revises: ac3c4166d51d
Create Date: 2026-09-26 17:29:06.602685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f74d8ed6718"
down_revision: Union[str, Sequence[str], None] = "ac3c4166d51d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_tag", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_courses_course_tag"), "courses", ["course_tag"], unique=True
    )
    op.create_table(
        "source_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("source_path", sa.String(length=1024), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_files_course_id"), "source_files", ["course_id"], unique=False
    )
    op.create_index(
        op.f("ix_source_files_document_id"),
        "source_files",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_files_source_path"),
        "source_files",
        ["source_path"],
        unique=True,
    )
    op.create_unique_constraint(
        "uq_chunks_document_id_chunk_index", "chunks", ["document_id", "chunk_index"]
    )
    op.drop_index(op.f("ix_documents_course_tag"), table_name="documents")
    op.drop_index(op.f("ix_documents_file_hash"), table_name="documents")
    op.create_index(
        op.f("ix_documents_file_hash"), "documents", ["file_hash"], unique=True
    )
    op.drop_column("documents", "course_tag")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "course_tag", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_documents_file_hash"), table_name="documents")
    op.create_index(
        op.f("ix_documents_file_hash"), "documents", ["file_hash"], unique=False
    )
    op.create_index(
        op.f("ix_documents_course_tag"), "documents", ["course_tag"], unique=False
    )
    op.drop_constraint("uq_chunks_document_id_chunk_index", "chunks", type_="unique")
    op.drop_index(op.f("ix_source_files_source_path"), table_name="source_files")
    op.drop_index(op.f("ix_source_files_document_id"), table_name="source_files")
    op.drop_index(op.f("ix_source_files_course_id"), table_name="source_files")
    op.drop_table("source_files")
    op.drop_index(op.f("ix_courses_course_tag"), table_name="courses")
    op.drop_table("courses")
    # ### end Alembic commands ###
