"""widen enum columns in documents

Revision ID: ac3c4166d51d
Revises: 3265b011cf26
Create Date: 2026-09-10 20:11:10.415930

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ac3c4166d51d"
down_revision: Union[str, Sequence[str], None] = "3265b011cf26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents",
        "status",
        existing_type=sa.VARCHAR(length=9),
        type_=sa.Enum(
            "PENDING",
            "EXTRACTED",
            "EMBEDDED",
            "FAILED",
            name="documentstatus",
            native_enum=False,
            length=20,
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "documents",
        "failure_reason",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "SOURCE_MISSING",
            "UNREADABLE_SOURCE",
            "NO_TEXT_EXTRACTED",
            "TEXT_BELOW_THRESHOLD",
            name="failurereason",
            native_enum=False,
            length=35,
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents",
        "failure_reason",
        existing_type=sa.Enum(
            "SOURCE_MISSING",
            "UNREADABLE_SOURCE",
            "NO_TEXT_EXTRACTED",
            "TEXT_BELOW_THRESHOLD",
            name="failurereason",
            native_enum=False,
            length=35,
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "documents",
        "status",
        existing_type=sa.Enum(
            "PENDING",
            "EXTRACTED",
            "EMBEDDED",
            "FAILED",
            name="documentstatus",
            native_enum=False,
            length=20,
        ),
        type_=sa.VARCHAR(length=9),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
